name: CI Build Major Branch


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are included
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi gcc-avr avrdude dfu-programmer dfu-util
  
    - name: Set up udev rules
      run: |
          sudo cp $GITHUB_WORKSPACE/util/udev/50-qmk.rules /etc/udev/rules.d/
          sudo udevadm control --reload-rules
          sudo udevadm trigger

    - name: Install qmk
      run: |
        pip install qmk
    - name: setup qmk
      run: |
        qmk setup
    - name: Compile mki
      run: |
        qmk compile -kb mki -km imi
    - uses: actions/upload-artifact@v3
      with:
        name: MKI
        path: ./.build/mki_imi.uf2
    
    - name: Compile mkii
      run: |
          qmk compile -kb mkii -km imi
    - uses: actions/upload-artifact@v3
      with:
          name: MKII
          path: ./.build/mkii_imi.uf2